---
title: "Exercises: `plotly`"
author: "Christina Maimone"
date: "`r Sys.Date()`"
output: html_document
params:
    answers: TRUE
---


```{r, echo=FALSE, eval=TRUE}
answers<-params$answers
```

```{r global_options, echo = FALSE, include = FALSE}
knitr::opts_chunk$set(echo=answers, eval=answers,
                      warning = FALSE, message = FALSE,
                      cache = FALSE, tidy = FALSE)
```

# Setup

```{r, echo=TRUE, eval=FALSE}
install.packages(c("tidyverse","babynames"))
```

```{r, echo=TRUE, eval=TRUE}
library(tidyverse)
library(babynames)
data(babynames)
```

Note: provided solutions use `dplyr`, but you can do the exercises without it.

# Exercise

Get the 100 most popular boy names in both 1880 and 2015.  For these names (top names from either year), make a scatter plot of the proportion of babies with the name in 2015 vs 1880.  Use plotly to add tooltips to the plot and zoom controls to help you explore.

```{asis}
### Solution

Pull the set of names that were in the top 100 in either year:
```

```{r}
m18802015 <- babynames %>%
  filter(year %in% c(1880, 2015) & sex == 'M') %>%
  group_by(year) %>%
  arrange(desc(prop)) %>%
  slice(1:100) %>%
  ungroup() %>%
  select(name) %>%
  distinct()
```

```{asis}
Get prop data for both years for this set of names
```

```{r}
bothyears <- m18802015 %>% 
  # add in data for 1880
  left_join(filter(babynames, year==1880 & sex == 'M'), 
            by="name") %>%
  ## clean up columns
  select(name, prop) %>%
  rename(prop1880 = prop) %>%
  ## add in data for 2015
  left_join(filter(babynames, year==2015 & sex == 'M'), 
            by="name") %>%
  ## clean up columns
  rename(prop2015 = prop) %>%
  select(name, prop1880, prop2015) %>%
  # fix missing to 0
  mutate(prop1880 = ifelse(is.na(prop1880), 0, prop1880),
         prop2015 = ifelse(is.na(prop2015), 0, prop2015))
```

```{r}
p1 <- bothyears %>% 
  ggplot(aes(y=prop2015, x=prop1880, label=name)) +
  geom_point() 
ggplotly(p1)
```


```{asis}
Note that the range on the two axes is very different.  

Or directly with plotly:
```

```{r}
plot_ly(bothyears, x=~prop1880, y=~prop2015,
        type="scatter",
        mode = "markers",
        text = ~name)
```

```{asis}
Or, with more formatting on the tooltips
```

```{r}
plot_ly(bothyears, x=~prop1880, y=~prop2015,
        type="scatter",
        mode = "markers",
        hoverinfo = "text",
        text = ~paste("1880:", round(prop1880, 4),
                      "<br>2015:", round(prop2015, 4),
                      "<br>Name:",name))
```


